(deftheme my-kanaga2
  "Created 2024-01-08.")

(custom-theme-set-faces
 'my-kanaga2
 '(default ((t (:family "Droid Sans Mono" :foundry "1ASC" :width normal :height 124 :weight regular :slant normal :underline nil :overline nil :extend nil :strike-through nil :box nil :inverse-video nil :foreground "#DCD7BA" :background "black" :stipple nil :inherit nil))))
 '(cursor ((t (:weight bold :foreground "#16161D" :background "#A3D4D5"))))
 '(fixed-pitch ((t (:family "Droid Sans Mono" :foundry "1ASC" :width normal :height 124 :weight regular :slant normal))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "navajo white"))))
 '(homoglyph ((t (:foreground "#A3D4D5"))))
 '(minibuffer-prompt ((t (:foreground "#E6C384" :background "#49443C"))))
 '(highlight ((t (:foreground "#938AA9" :background "#54536D"))))
 '(region ((t (:extend t :background "#2D4F67"))))
 '(shadow ((t (:background "#16161D"))))
 '(secondary-selection ((((class color) (min-colors 88) (background light)) (:extend t :background "yellow1")) (((class color) (min-colors 88) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 16) (background light)) (:extend t :background "yellow")) (((class color) (min-colors 16) (background dark)) (:extend t :background "SkyBlue4")) (((class color) (min-colors 8)) (:extend t :foreground "black" :background "cyan")) (t (:inverse-video t))))
 '(trailing-whitespace ((t (:background "#54536D"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#7FB4CA"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#727169"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#727169"))))
 '(font-lock-constant-face ((t (:foreground "#E6C384"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#54536D"))))
 '(font-lock-doc-markup-face ((t (:foreground "#54536D"))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:foreground "#7E9CD8"))))
 '(font-lock-keyword-face ((t (:weight semi-bold :foreground "#957FB8"))))
 '(font-lock-negation-char-face ((t (:foreground "#FF5D62"))))
 '(font-lock-number-face ((t nil)))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:foreground "#C0A36E"))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t nil)))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#C0A36E"))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:slant italic :foreground "#98BB6C"))))
 '(font-lock-type-face ((t (:foreground "#7AA89F"))))
 '(font-lock-variable-name-face ((t (:foreground "#E46876"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#FF9E3B"))))
 '(button ((t (:foreground "#7AA89F"))))
 '(link ((t (:foreground "#7E9CD8"))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:foreground "#363646"))))
 '(header-line ((t (:background "#16161D"))))
 '(tooltip ((t (:weight bold :foreground "#16161D" :background "#E6C384"))))
 '(mode-line ((t (:background "#16161D"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#7AA89F"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((t (:foreground "#C0A36E"))))
 '(mode-line-inactive ((t (:weight normal :foreground "#54546D"))))
 '(isearch ((((class color) (min-colors 88) (background light)) (:foreground "lightskyblue1" :background "magenta3")) (((class color) (min-colors 88) (background dark)) (:foreground "brown4" :background "palevioletred2")) (((class color) (min-colors 16)) (:foreground "cyan1" :background "magenta4")) (((class color) (min-colors 8)) (:foreground "cyan1" :background "magenta4")) (t (:inverse-video t))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((((class color) (min-colors 88) (background light)) (:distant-foreground "black" :background "paleturquoise")) (((class color) (min-colors 88) (background dark)) (:distant-foreground "white" :background "paleturquoise4")) (((class color) (min-colors 16)) (:distant-foreground "white" :background "turquoise3")) (((class color) (min-colors 8)) (:distant-foreground "white" :background "turquoise3")) (t (:underline (:color foreground-color :style line :position nil)))))
 '(match ((t (:foreground "#16161D" :background "#E6C384"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'my-kanaga2)
