(deftheme my-vscode
  "Created 2024-01-06.")

(custom-theme-set-faces
 'my-vscode
 '(default ((t (:inherit nil :extend nil :stipple nil :background "black" :foreground "#d4d4d4" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight regular :height 124 :width normal :foundry "1ASC" :family "Droid Sans Mono"))))
 '(cursor ((t (:background "#d4d4d4"))))
 '(fixed-pitch ((t (:family "Droid Sans Mono" :foundry "1ASC" :width normal :height 124 :weight regular :slant normal))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:weight normal :foreground "#4ec9b0"))))
 '(highlight ((t (:underline (:color foreground-color :style line :position nil) :foreground "#4db2ff"))))
 '(region ((t (:extend nil :background "#264f78"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:inherit (region)))))
 '(trailing-whitespace ((t (:background "#f16969"))))
 '(font-lock-bracket-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-builtin-face ((t (:foreground "#c586c0"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#6a9955"))))
 '(font-lock-constant-face ((t (:foreground "#569cd6"))))
 '(font-lock-delimiter-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-doc-face ((t (:foreground "#ce9178"))))
 '(font-lock-doc-markup-face ((t (:inherit (font-lock-constant-face)))))
 '(font-lock-escape-face ((t (:inherit (font-lock-regexp-grouping-backslash)))))
 '(font-lock-function-call-face ((t (:inherit (font-lock-function-name-face)))))
 '(font-lock-function-name-face ((t (:weight normal :foreground "#dcdcaa"))))
 '(font-lock-keyword-face ((t (:weight normal :foreground "#569cd6"))))
 '(font-lock-negation-char-face ((t (:foreground "#569cd6"))))
 '(font-lock-number-face ((t (:foreground "#b5cea8"))))
 '(font-lock-misc-punctuation-face ((t (:inherit (font-lock-punctuation-face)))))
 '(font-lock-operator-face ((t (:inherit (default)))))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-property-name-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-property-use-face ((t (:inherit (font-lock-property-name-face)))))
 '(font-lock-punctuation-face ((t (:inherit (default)))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#d7ba7d"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#d7ba7d"))))
 '(font-lock-string-face ((t (:foreground "#ce9178"))))
 '(font-lock-type-face ((t (:foreground "#4ec9b0"))))
 '(font-lock-variable-name-face ((t (:foreground "#9cdcfe"))))
 '(font-lock-variable-use-face ((t (:inherit (font-lock-variable-name-face)))))
 '(font-lock-warning-face ((t (:foreground "#f16969" :background "#252526"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "#3794ff"))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#fafafa"))))
 '(header-line ((t (:background "#333333" :foreground "#fafafa" :weight normal))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:background "blue4" :foreground "#fafafa" :weight normal))))
 '(mode-line-buffer-id ((t (:weight normal :foreground "#ffffff"))))
 '(mode-line-emphasis ((t (:foreground "#d4d4d4"))))
 '(mode-line-highlight ((t (:weight normal :box nil :foreground "#569cd6"))))
 '(mode-line-inactive ((t (:weight normal :foreground "#d4d4d4" :background "#005aa3"))))
 '(isearch ((t (:background "#613214"))))
 '(isearch-fail ((((class color) (min-colors 88) (background light)) (:background "RosyBrown1")) (((class color) (min-colors 88) (background dark)) (:background "red4")) (((class color) (min-colors 16)) (:background "red")) (((class color) (min-colors 8)) (:background "red")) (((class color grayscale)) (:foreground "grey")) (t (:inverse-video t))))
 '(lazy-highlight ((t (:background "#613214"))))
 '(match ((((class color) (min-colors 88) (background light)) (:background "khaki1")) (((class color) (min-colors 88) (background dark)) (:background "RoyalBlue3")) (((class color) (min-colors 8) (background light)) (:foreground "black" :background "yellow")) (((class color) (min-colors 8) (background dark)) (:foreground "white" :background "blue")) (((type tty) (class mono)) (:inverse-video t)) (t (:background "gray"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'my-vscode)
